name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  playwright_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm and playwright
        run: |
          npm install
          npx playwright install
          
      - name: Run playwright tests
        run:
          npx playwright test